"""add_paid_status_and_paid_at_to_bill_occurrences

Revision ID: 45224bc544de
Revises: 5a09d424eeaf
Create Date: 2026-03-15 15:21:12.899558
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45224bc544de'
down_revision: Union[str, None] = '5a09d424eeaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add 'PAID' value to the occurrencestatus enum type (uppercase to match existing values)
    op.execute("ALTER TYPE occurrencestatus ADD VALUE IF NOT EXISTS 'PAID'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_occurrences', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill_occurrences', 'paid_at')
    # ### end Alembic commands ###
    # Note: PostgreSQL does not support removing enum values; this is a no-op for the enum
