"""add_matched_invoice_id_to_bill_occurrences

Revision ID: 513185f436be
Revises: 45224bc544de
Create Date: 2026-03-15 15:32:55.434388
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513185f436be'
down_revision: Union[str, None] = '45224bc544de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_occurrences', sa.Column('matched_invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bill_occurrences', 'invoices', ['matched_invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bill_occurrences', type_='foreignkey')
    op.drop_column('bill_occurrences', 'matched_invoice_id')
    # ### end Alembic commands ###
